---

- name: start and enable service
  ansible.builtin.service:
    name: paperless-config
    state: "{{ paperless_service.state | default('started') }}"
    enabled: "{{ paperless_service.enabled | default('true') | bool }}"
  tags:
    - paperless
    - paperless-service

- name: start and enable service
  ansible.builtin.service:
    name: paperless
    state: "{{ paperless_service.state | default('started') }}"
    enabled: "{{ paperless_service.enabled | default('true') | bool }}"
  tags:
    - paperless
    - paperless-service

...
