---

docker_config:
  data_root: /opt/docker
  max_concurrent_downloads: 10
  debug: false
  experimental: true
  hosts:
    - unix:///var/run/docker.sock
  tls: false
  tlsverify: false
  log_driver: "json-file"
  log_opts:
    "max-size": "10m"
    "max-file": "3"
    mode: non-blocking
    max-buffer-size: 4m
